In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.

In [3]:
#loading the native dataset
df_native = pd.read_parquet(r'C:\Users\samya\PyCharmProject\Predictive-SDN-Dynamic-Load-Balancer_data\data\ml\traffic_network_native.parquet')
df_native.head()

,id,event_id,event_timestamp,source_node,destination_node,source_ip,destination_ip,protocol,packet_count,byte_count,duration_ms,throughput_mbps,packet_loss_percent,latency_ms,raw_payload,kafka_topic,kafka_partition,kafka_offset,ingested_at
0,1,abilene_20040301-0000_ATLAM5_ATLAng,2004-03-01 00:00:00+00:00,ATLAM5,ATLAng,None,None,None,None,None,None,0.522208,None,None,"{'unit': 'MBITPERSEC', 'dataset': 'abilene', '...",traffic.validated,0,0,2026-09-10 11:02:54.698593+00:00
1,2,abilene_20040301-0000_ATLAM5_SNVAng,2004-03-01 00:00:00+00:00,ATLAM5,SNVAng,None,None,None,None,None,None,0.747405,None,None,"{'unit': 'MBITPERSEC', 'dataset': 'abilene', '...",traffic.validated,0,1,2026-09-10 11:26:26.963746+00:00
2,3,abilene_20040301-0000_ATLAng_ATLAM5,2004-03-01 00:00:00+00:00,ATLAng,ATLAM5,None,None,None,None,None,None,0.445149,None,None,"{'unit': 'MBITPERSEC', 'dataset': 'abilene', '...",traffic.validated,2,0,2026-09-10 11:26:32.567970+00:00
3,4,abilene_20040301-0000_ATLAng_CHINng,2004-03-01 00:00:00+00:00,ATLAng,CHINng,None,None,None,None,None,None,16.283117,None,None,"{'unit': 'MBITPERSEC', 'dataset': 'abilene', '...",traffic.validated,0,2,2026-09-10 11:26:32.567970+00:00
4,5,abilene_20040301-0000_ATLAng_HSTNng,2004-03-01 00:00:00+00:00,ATLAng,HSTNng,None,None,None,None,None,None,3.931403,None,None,"{'unit': 'MBITPERSEC', 'dataset': 'abilene', '...",traffic.validated,0,3,2026-09-10 11:26:32.567970+00:00

In [4]:
df_native.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6015948 entries, 0 to 6015947
Data columns (total 19 columns):
 #   Column               Dtype
---  ------               -----
 0   id                   int64
 1   event_id             object
 2   event_timestamp      datetime64[us, UTC]
 3   source_node          object
 4   destination_node     object
 5   source_ip            object
 6   destination_ip       object
 7   protocol             object
 8   packet_count         object
 9   byte_count           object
 10  duration_ms          object
 11  throughput_mbps      float64
 12  packet_loss_percent  object
 13  latency_ms           object
 14  raw_payload          object
 15  kafka_topic          object
 16  kafka_partition      int64
 17  kafka_offset         int64
 18  ingested_at          datetime64[us, UTC]
dtypes: datetime64[us, UTC](2), float64(1), int64(3), object(13)
memory usage: 872.1+ MB

In [6]:
df_native.tail()

,id,event_id,event_timestamp,source_node,destination_node,source_ip,destination_ip,protocol,packet_count,byte_count,duration_ms,throughput_mbps,packet_loss_percent,latency_ms,raw_payload,kafka_topic,kafka_partition,kafka_offset,ingested_at
6015943,11990627,abilene_20040910-2355_CHINng_STTLng,2004-09-10 23:55:00+00:00,CHINng,STTLng,None,None,None,None,None,None,26.664448,None,None,"{'unit': 'MBITPERSEC', 'dataset': 'abilene', '...",traffic.validated,2,2010930,2026-09-11 06:22:13.125770+00:00
6015944,11990628,abilene_20040910-2355_CHINng_WASHng,2004-09-10 23:55:00+00:00,CHINng,WASHng,None,None,None,None,None,None,36.155136,None,None,"{'unit': 'MBITPERSEC', 'dataset': 'abilene', '...",traffic.validated,2,2010931,2026-09-11 06:22:13.125770+00:00
6015945,11990629,abilene_20040910-2355_DNVRng_WASHng,2004-09-10 23:55:00+00:00,DNVRng,WASHng,None,None,None,None,None,None,27.722376,None,None,"{'unit': 'MBITPERSEC', 'dataset': 'abilene', '...",traffic.validated,2,2010932,2026-09-11 06:22:13.125770+00:00
6015946,11990630,abilene_20040910-2355_KSCYng_DNVRng,2004-09-10 23:55:00+00:00,KSCYng,DNVRng,None,None,None,None,None,None,8.520211,None,None,"{'unit': 'MBITPERSEC', 'dataset': 'abilene', '...",traffic.validated,2,2010933,2026-09-11 06:22:13.125770+00:00
6015947,11990631,abilene_20040910-2355_KSCYng_SNVAng,2004-09-10 23:55:00+00:00,KSCYng,SNVAng,None,None,None,None,None,None,2.677619,None,None,"{'unit': 'MBITPERSEC', 'dataset': 'abilene', '...",traffic.validated,2,2010934,2026-09-11 06:22:13.125770+00:00

In [7]:
df_native.shape

(6015948, 19)

In [9]:
df_xml= pd.read_parquet(r'C:\Users\samya\PyCharmProject\Predictive-SDN-Dynamic-Load-Balancer_data\data\ml\traffic_xml_raw.parquet') 
df_xml.head()

,record_id,event_id,demand_id,timestamp,timestamp_raw,source_node,destination_node,source_longitude,source_latitude,destination_longitude,...,traffic_raw,dataset,granularity,unit,network_version,origin,source_file,source_path,source_format,schema_version
0,baff32855ba96e43293d4091a5ba50294b92deb7d3ba61...,eafa2b59d6cfe29e796560889f3ac1f28369620ce76ca5...,ATLAM5_ATLAng,2004-03-01 00:00:00+00:00,20040301-0000,ATLAM5,ATLAng,NaN,NaN,NaN,...,0.522208,directed-abilene-zhang-5min-over-6months-ALL,5min,MBITPERSEC,None,"Yin Zhang, http://userweb.cs.utexas.edu/~yzhan...",demandMatrix-abilene-zhang-5min-20040301-0000.xml,C:\Users\samya\PyCharmProject\Predictive-SDN-D...,SNDLib XML,1.0
1,bdeb5a3af4ceea83d5307fe5b3481b5978d9daf122ffe9...,4fc41445720ed7bd35ff8d937fb926b5302ecfd5a1cb80...,ATLAM5_CHINng,2004-03-01 00:00:00+00:00,20040301-0000,ATLAM5,CHINng,NaN,NaN,NaN,...,1.641339,directed-abilene-zhang-5min-over-6months-ALL,5min,MBITPERSEC,None,"Yin Zhang, http://userweb.cs.utexas.edu/~yzhan...",demandMatrix-abilene-zhang-5min-20040301-0000.xml,C:\Users\samya\PyCharmProject\Predictive-SDN-D...,SNDLib XML,1.0
2,5285b485e50d57f8b70304fb2b617b8ce5f205422433ef...,1ad22f3c3678a48d2f07026cc27abadafab65333332082...,ATLAM5_DNVRng,2004-03-01 00:00:00+00:00,20040301-0000,ATLAM5,DNVRng,NaN,NaN,NaN,...,0.335728,directed-abilene-zhang-5min-over-6months-ALL,5min,MBITPERSEC,None,"Yin Zhang, http://userweb.cs.utexas.edu/~yzhan...",demandMatrix-abilene-zhang-5min-20040301-0000.xml,C:\Users\samya\PyCharmProject\Predictive-SDN-D...,SNDLib XML,1.0
3,07cd6d5c920f513fe9ba28bcdb59afa08b644e504a6967...,374c34a8420725bf6f4a2835387a2dc831cb861bea3eb7...,ATLAM5_HSTNng,2004-03-01 00:00:00+00:00,20040301-0000,ATLAM5,HSTNng,NaN,NaN,NaN,...,0.413032,directed-abilene-zhang-5min-over-6months-ALL,5min,MBITPERSEC,None,"Yin Zhang, http://userweb.cs.utexas.edu/~yzhan...",demandMatrix-abilene-zhang-5min-20040301-0000.xml,C:\Users\samya\PyCharmProject\Predictive-SDN-D...,SNDLib XML,1.0
4,671d448c86c7634ba17a3ce317c1943b0a780764b152a0...,4fa4dce7221feba8a43fa55f85d1b74cb6c7a680243a0b...,ATLAM5_IPLSng,2004-03-01 00:00:00+00:00,20040301-0000,ATLAM5,IPLSng,NaN,NaN,NaN,...,0.489875,directed-abilene-zhang-5min-over-6months-ALL,5min,MBITPERSEC,None,"Yin Zhang, http://userweb.cs.utexas.edu/~yzhan...",demandMatrix-abilene-zhang-5min-20040301-0000.xml,C:\Users\samya\PyCharmProject\Predictive-SDN-D...,SNDLib XML,1.0

In [11]:
df_xml.shape

(6015975, 22)

In [12]:
df_native.describe()

                 id  throughput_mbps  kafka_partition  kafka_offset
count  6.015948e+06     6.015948e+06     6.015948e+06  6.015948e+06
mean   6.020885e+06     2.271585e+01     1.000090e+00  1.004624e+06
std    3.483459e+06     8.616978e+01     8.164510e-01  5.805517e+05
min    1.000000e+00     1.333300e-02     0.000000e+00  0.000000e+00
25%    2.961193e+06     1.913496e+00     0.000000e+00  5.015238e+05
50%    5.998130e+06     9.564097e+00     1.000000e+00  1.004264e+06
75%    8.987838e+06     2.622496e+01     2.000000e+00  1.506327e+06
max    1.199063e+07     7.085251e+03     2.000000e+00  2.011495e+06

In [13]:
df_xml.describe()

,source_longitude,source_latitude,destination_longitude,destination_latitude,traffic_mbps
count,0.0,0.0,0.0,0.0,6.015975e+06
mean,NaN,NaN,NaN,NaN,2.271586e+01
std,NaN,NaN,NaN,NaN,8.616962e+01
min,NaN,NaN,NaN,NaN,1.333300e-02
25%,NaN,NaN,NaN,NaN,1.913499e+00
50%,NaN,NaN,NaN,NaN,9.564115e+00
75%,NaN,NaN,NaN,NaN,2.622497e+01
max,NaN,NaN,NaN,NaN,7.085251e+03

In [14]:
df_native.isnull().sum()

id                           0
event_id                     0
event_timestamp              0
source_node                  0
destination_node             0
source_ip              6015948
destination_ip         6015948
protocol               6015948
packet_count           6015948
byte_count             6015948
duration_ms            6015948
throughput_mbps              0
packet_loss_percent    6015948
latency_ms             6015948
raw_payload                  0
kafka_topic                  0
kafka_partition              0
kafka_offset                 0
ingested_at                  0
dtype: int64

In [16]:
df_xml.isnull().sum()

record_id                      0
event_id                       0
demand_id                      0
timestamp                      0
timestamp_raw                  0
source_node                    0
destination_node               0
source_longitude         6015975
source_latitude          6015975
destination_longitude    6015975
destination_latitude     6015975
traffic_mbps                   0
traffic_raw                    0
dataset                        0
granularity                    0
unit                           0
network_version          6015975
origin                         0
source_file                    0
source_path                    0
source_format                  0
schema_version                 0
dtype: int64

In [17]:
missing_percent = (
    df_native.isna().mean() * 100
).sort_values(ascending=False)

missing_percent

packet_count           100.0
source_ip              100.0
destination_ip         100.0
byte_count             100.0
duration_ms            100.0
latency_ms             100.0
protocol               100.0
packet_loss_percent    100.0
event_timestamp          0.0
id                       0.0
event_id                 0.0
destination_node         0.0
source_node              0.0
throughput_mbps          0.0
raw_payload              0.0
kafka_topic              0.0
kafka_partition          0.0
kafka_offset             0.0
ingested_at              0.0
dtype: float64

In [18]:
missing_percent = (
    df_xml.isna().mean() * 100
).sort_values(ascending=False)

missing_percent

source_latitude          100.0
network_version          100.0
destination_latitude     100.0
destination_longitude    100.0
source_longitude         100.0
record_id                  0.0
source_node                0.0
timestamp_raw              0.0
timestamp                  0.0
demand_id                  0.0
event_id                   0.0
destination_node           0.0
traffic_raw                0.0
traffic_mbps               0.0
dataset                    0.0
granularity                0.0
unit                       0.0
origin                     0.0
source_file                0.0
source_path                0.0
source_format              0.0
schema_version             0.0
dtype: float64

In [19]:
print("Total rows:", len(df_native))
print("Unique event IDs:", df_native["event_id"].nunique())
print("Duplicate event IDs:", df_native["event_id"].duplicated().sum())

Total rows: 6015948
Unique event IDs: 6015948
Duplicate event IDs: 0

In [20]:
print("Total rows:", len(df_xml))
print("Unique event IDs:", df_xml["event_id"].nunique())
print("Duplicate event IDs:", df_xml["event_id"].duplicated().sum())

Total rows: 6015975
Unique event IDs: 6015975
Duplicate event IDs: 0

In [23]:
print("Unique timestamps:", df_xml["timestamp"].nunique())
print("Unique source nodes:", df_xml["source_node"].nunique())
print("Unique destination nodes:", df_xml["destination_node"].nunique())

pairs = df_xml[
    ["source_node", "destination_node"]
].drop_duplicates()

print("Unique directed pairs:", len(pairs))

Unique timestamps: 48096
Unique source nodes: 12
Unique destination nodes: 12
Unique directed pairs: 132

In [22]:
print("Unique timestamps:", df_native["event_timestamp"].nunique())
print("Unique source nodes:", df_native["source_node"].nunique())
print("Unique destination nodes:", df_native["destination_node"].nunique())

pairs = df_native[
    ["source_node", "destination_node"]
].drop_duplicates()

print("Unique directed pairs:", len(pairs))

Unique timestamps: 48096
Unique source nodes: 12
Unique destination nodes: 12
Unique directed pairs: 132